"""Build vocab-recall answer keys: validate words, compute pinyin + tones.

    python gen_vocab.py            # validate + write vocab_data.js for every vocab/hsk<N>/*.json
    python gen_vocab.py --check    # validate only, no output file

Unlike the listening sets (hsk_vocab.load_level, which allows the *cumulative*
HSK1..N vocabulary), a vocab-recall item's `word` must be an EXACT entry in
that level's own new-word list (data/vocab/raw/hsk_2012_L<N>.txt) -- the whole
point is drilling the words newly introduced at that level, not anything
carried over from a lower one.

Pinyin and tones are never hand-typed: pypinyin computes the plain reading and
a per-syllable tone digit, dropping genuinely neutral-tone syllables (as
determined by pypinyin's dictionary, not guessed) to match the answer format
"piaoliang 4" rather than "piaoliang 45".
"""

import argparse
import json
import re
import sys
from pathlib import Path

from pypinyin import Style, pinyin

ROOT = Path(__file__).parent
VOCAB_TESTS = ROOT / "vocab"
RAW = ROOT / "data" / "vocab" / "raw"
OUT = ROOT / "vocab_data.js"

LEVEL_DIR = re.compile(r"^hsk(\d+)$", re.IGNORECASE)


def level_only_words(level: int) -> set[str]:
    """Words newly introduced at exactly this level (NOT cumulative)."""
    path = RAW / f"hsk_2012_L{level}.txt"
    if not path.exists():
        raise FileNotFoundError(f"HSK{level} needs {path} -- not downloaded yet")
    words = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        w = line.strip().lstrip("﻿")
        if w and not w.startswith("#"):
            words.add(w)
    return words


def answer_key(word: str) -> dict:
    plain = "".join(seg[0] for seg in pinyin(word, style=Style.NORMAL))
    tone_syllables = [seg[0] for seg in pinyin(word, style=Style.TONE3, neutral_tone_with_five=True)]
    tones_full = [s[-1] for s in tone_syllables]  # trailing digit per syllable, "5" = neutral
    tone_compact = "".join(t for t in tones_full if t != "5")
    return {"pinyin": plain, "tones_full": "".join(tones_full), "tones_compact": tone_compact}


def load_sets() -> list[dict]:
    sets = []
    for level_dir in sorted(p for p in VOCAB_TESTS.iterdir() if p.is_dir()):
        m = LEVEL_DIR.match(level_dir.name)
        if not m:
            sys.exit(f"vocab/{level_dir.name}/ does not match the hsk<N> naming convention")
        level = int(m.group(1))
        for f in sorted(level_dir.glob("*.json")):
            s = json.loads(f.read_text(encoding="utf-8"))
            declared = s.get("level", "")
            if declared.upper() != f"HSK{level}":
                sys.exit(
                    f"{f}: level field is {declared!r} but the file lives under "
                    f"vocab/{level_dir.name}/ -- fix one or the other"
                )
            s["_level_num"] = level
            s["key"] = f"{level_dir.name}/{f.stem}"
            sets.append(s)
    if not sets:
        sys.exit(f"no sets found under {VOCAB_TESTS} (expected vocab/hsk<N>/*.json)")
    return sets


def validate(sets: list[dict]) -> int:
    failures = 0
    for s in sets:
        allowed = level_only_words(s["_level_num"])
        print(f"\n[{s['key']}] {s['title']}  ({len(s['items'])} items, HSK{s['_level_num']}-only vocab={len(allowed)} words)")
        for item in s["items"]:
            word = item["word"]
            if word not in allowed:
                failures += 1
                print(f"  NG {item['n']:>2}. {word}  -- not a new HSK{s['_level_num']} word (check data/vocab/raw/hsk_2012_L{s['_level_num']}.txt)")
                continue
            key = answer_key(word)
            print(f"  ok {item['n']:>2}. {word}  {key['pinyin']} {key['tones_compact']}")
    return failures


def write_output(sets: list[dict]) -> None:
    for s in sets:
        for item in s["items"]:
            item.update(answer_key(item["word"]))
        s.pop("_level_num", None)
    body = json.dumps(sets, ensure_ascii=False, indent=2)
    OUT.write_text(f"// generated by gen_vocab.py -- do not edit\nwindow.VOCAB_DATA = {body};\n", encoding="utf-8")
    total = sum(len(s["items"]) for s in sets)
    print(f"\nwrote {OUT.name}: {len(sets)} set(s), {total} items")


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate only, no output file")
    args = ap.parse_args()

    sets = load_sets()
    failures = validate(sets)
    if failures:
        sys.exit(f"\n{failures} word(s) are not new-to-level vocabulary. Fix them or pick a different word.")
    print("\nvocabulary: all words are genuinely new at their declared HSK level.")

    if args.check:
        return
    write_output(sets)


if __name__ == "__main__":
    main()
