// generated by gen.py -- do not edit
window.TEST_DATA = [
  {
    "id": "set_001",
    "title": "HSK2 リスニング 1文ずつ (1)",
    "level": "HSK2",
    "sentences": [
      {
        "n": 1,
        "zh": "我早上七点起床。",
        "ja": "私は朝7時に起きます。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s01.mp3",
        "pinyin": "wǒ zǎo shàng qī diǎn qǐ chuáng。"
      },
      {
        "n": 2,
        "zh": "今天天气非常好。",
        "ja": "今日は天気がとても良いです。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s02.mp3",
        "pinyin": "jīn tiān tiān qì fēi cháng hǎo。"
      },
      {
        "n": 3,
        "zh": "你的手机是新的吗？",
        "ja": "あなたの携帯電話は新しいものですか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s03.mp3",
        "pinyin": "nǐ de shǒu jī shì xīn de ma？"
      },
      {
        "n": 4,
        "zh": "这个西瓜太贵了，我不买。",
        "ja": "このスイカは高すぎるので、私は買いません。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s04.mp3",
        "pinyin": "zhè ge xī guā tài guì le， wǒ bù mǎi。"
      },
      {
        "n": 5,
        "zh": "他昨天生病了，所以没来上班。",
        "ja": "彼は昨日病気になったので、出勤しませんでした。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s05.mp3",
        "pinyin": "tā zuó tiān shēng bìng le， suǒ yǐ méi lái shàng bān。"
      },
      {
        "n": 6,
        "zh": "我妹妹正在房间里睡觉。",
        "ja": "妹は今、部屋で寝ています。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s06.mp3",
        "pinyin": "wǒ mèi mèi zhèng zài fáng jiān lǐ shuì jiào。"
      },
      {
        "n": 7,
        "zh": "请问，火车站离这儿远吗？",
        "ja": "すみません、駅はここから遠いですか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s07.mp3",
        "pinyin": "qǐng wèn， huǒ chē zhàn lí zhè ér yuǎn ma？"
      },
      {
        "n": 8,
        "zh": "我觉得学习汉语很有意思。",
        "ja": "私は中国語を勉強するのはとても面白いと思います。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s08.mp3",
        "pinyin": "wǒ jué de xué xí hàn yǔ hěn yǒu yì si。"
      },
      {
        "n": 9,
        "zh": "你会说汉语吗？我会说一点儿。",
        "ja": "あなたは中国語を話せますか。私は少し話せます。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s09.mp3",
        "pinyin": "nǐ huì shuō hàn yǔ ma？ wǒ huì shuō yì diǎn ér。"
      },
      {
        "n": 10,
        "zh": "明天是我姐姐的生日。",
        "ja": "明日は姉の誕生日です。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s10.mp3",
        "pinyin": "míng tiān shì wǒ jiě jiě de shēng rì。"
      },
      {
        "n": 11,
        "zh": "这件衣服是红的，很漂亮。",
        "ja": "この服は赤くて、とてもきれいです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s11.mp3",
        "pinyin": "zhè jiàn yī fú shì hóng de， hěn piào liàng。"
      },
      {
        "n": 12,
        "zh": "因为下雨，所以我们没去踢足球。",
        "ja": "雨が降ったので、私たちはサッカーをしに行きませんでした。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s12.mp3",
        "pinyin": "yīn wèi xià yǔ， suǒ yǐ wǒ men méi qù tī zú qiú。"
      },
      {
        "n": 13,
        "zh": "我哥哥在公司工作，他非常忙。",
        "ja": "兄は会社で働いていて、とても忙しいです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s13.mp3",
        "pinyin": "wǒ gē gē zài gōng sī gōng zuò， tā fēi cháng máng。"
      },
      {
        "n": 14,
        "zh": "你知道那个人叫什么名字吗？",
        "ja": "あなたはあの人が何という名前か知っていますか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s14.mp3",
        "pinyin": "nǐ zhī dào nà ge rén jiào shén me míng zì ma？"
      },
      {
        "n": 15,
        "zh": "老师让我们读书，也让我们写字。",
        "ja": "先生は私たちに本を読ませ、字も書かせます。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s15.mp3",
        "pinyin": "lǎo shī ràng wǒ men dú shū， yě ràng wǒ men xiě zì。"
      },
      {
        "n": 16,
        "zh": "我已经吃过米饭了，不想吃面条。",
        "ja": "私はもうご飯を食べたので、麺は食べたくありません。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s16.mp3",
        "pinyin": "wǒ yǐ jīng chī guò mǐ fàn le， bù xiǎng chī miàn tiáo。"
      },
      {
        "n": 17,
        "zh": "请你介绍一下你的新同学。",
        "ja": "あなたの新しいクラスメートを少し紹介してください。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s17.mp3",
        "pinyin": "qǐng nǐ jiè shào yī xià nǐ de xīn tóng xué。"
      },
      {
        "n": 18,
        "zh": "桌子上有两本书和一个手机。",
        "ja": "机の上に本が2冊と携帯電話が1台あります。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s18.mp3",
        "pinyin": "zhuō zi shàng yǒu liǎng běn shū hé yí gè shǒu jī。"
      },
      {
        "n": 19,
        "zh": "弟弟非常喜欢跑步，也喜欢游泳。",
        "ja": "弟はランニングが大好きで、水泳も好きです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s19.mp3",
        "pinyin": "dì di fēi cháng xǐ huān pǎo bù， yě xǐ huān yóu yǒng。"
      },
      {
        "n": 20,
        "zh": "我想去中国旅游，但是没有时间。",
        "ja": "私は中国へ旅行に行きたいですが、時間がありません。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s20.mp3",
        "pinyin": "wǒ xiǎng qù zhōng guó lǚ yóu， dàn shì méi yǒu shí jiān。"
      },
      {
        "n": 21,
        "zh": "你从哪儿来？我从北京来。",
        "ja": "あなたはどこから来ましたか。私は北京から来ました。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s21.mp3",
        "pinyin": "nǐ cóng nǎ ér lái？ wǒ cóng běi jīng lái。"
      },
      {
        "n": 22,
        "zh": "我们坐出租车去机场吧。",
        "ja": "私たちはタクシーで空港へ行きましょう。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s22.mp3",
        "pinyin": "wǒ men zuò chū zū chē qù jī chǎng ba。"
      },
      {
        "n": 23,
        "zh": "他喜欢唱歌，也喜欢跳舞。",
        "ja": "彼は歌うのが好きで、踊るのも好きです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s23.mp3",
        "pinyin": "tā xǐ huān chàng gē， yě xǐ huān tiào wǔ。"
      },
      {
        "n": 24,
        "zh": "这个问题我不懂，你可以帮助我吗？",
        "ja": "この問題が私には分かりません、手伝ってもらえますか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s24.mp3",
        "pinyin": "zhè ge wèn tí wǒ bù dǒng， nǐ kě yǐ bāng zhù wǒ ma？"
      },
      {
        "n": 25,
        "zh": "服务员，这个菜多少钱？",
        "ja": "店員さん、この料理はいくらですか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s25.mp3",
        "pinyin": "fú wù yuán， zhè ge cài duō shǎo qián？"
      },
      {
        "n": 26,
        "zh": "医生说我要多休息，多喝水。",
        "ja": "医者は、私にもっと休んで、水をたくさん飲むようにと言いました。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s26.mp3",
        "pinyin": "yī shēng shuō wǒ yào duō xiū xī， duō hē shuǐ。"
      },
      {
        "n": 27,
        "zh": "今天很冷，你穿这件衣服吧。",
        "ja": "今日は寒いので、この服を着てください。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s27.mp3",
        "pinyin": "jīn tiān hěn lěng， nǐ chuān zhè jiàn yī fú ba。"
      },
      {
        "n": 28,
        "zh": "我的眼睛很累，我想休息一下。",
        "ja": "私は目が疲れたので、少し休みたいです。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s28.mp3",
        "pinyin": "wǒ de yǎn jīng hěn lèi， wǒ xiǎng xiū xī yī xià。"
      },
      {
        "n": 29,
        "zh": "她写字写得很漂亮。",
        "ja": "彼女は字を書くのがとてもきれいです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_001/s29.mp3",
        "pinyin": "tā xiě zì xiě dé hěn piào liàng。"
      },
      {
        "n": 30,
        "zh": "昨天我在商店买了一个杯子。",
        "ja": "昨日、私は店でコップを1つ買いました。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_001/s30.mp3",
        "pinyin": "zuó tiān wǒ zài shāng diàn mǎi le yí gè bēi zi。"
      }
    ],
    "key": "hsk2/set_001"
  },
  {
    "id": "set_002",
    "title": "HSK2 リスニング 1文ずつ (2)",
    "level": "HSK2",
    "sentences": [
      {
        "n": 1,
        "zh": "你想喝咖啡还是喝茶？",
        "ja": "コーヒーを飲みたいですか、それともお茶を飲みたいですか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s01.mp3",
        "pinyin": "nǐ xiǎng hē kā fēi hái shì hē chá？"
      },
      {
        "n": 2,
        "zh": "我们家旁边有一个很大的商店。",
        "ja": "私たちの家の隣に大きなお店があります。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s02.mp3",
        "pinyin": "wǒ men jiā páng biān yǒu yí gè hěn dà de shāng diàn。"
      },
      {
        "n": 3,
        "zh": "妈妈希望我早上回家。",
        "ja": "母は私に朝のうちに帰ってきてほしいと思っています。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s03.mp3",
        "pinyin": "mā mā xī wàng wǒ zǎo shàng huí jiā。"
      },
      {
        "n": 4,
        "zh": "这个字怎么写？我不认识。",
        "ja": "この字はどう書きますか。私は知りません(読めません)。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s04.mp3",
        "pinyin": "zhè ge zì zěn me xiě？ wǒ bù rèn shí。"
      },
      {
        "n": 5,
        "zh": "你的汉语说得怎么样？",
        "ja": "あなたの中国語はどれくらい上手に話せますか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s05.mp3",
        "pinyin": "nǐ de hàn yǔ shuō dé zěn me yàng？"
      },
      {
        "n": 6,
        "zh": "我朋友的猫很漂亮。",
        "ja": "私の友達の猫はとてもきれいです。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s06.mp3",
        "pinyin": "wǒ péng yǒu de māo hěn piào liàng。"
      },
      {
        "n": 7,
        "zh": "我想买一件新衣服。",
        "ja": "私は新しい服を1着買いたいです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s07.mp3",
        "pinyin": "wǒ xiǎng mǎi yī jiàn xīn yī fú。"
      },
      {
        "n": 8,
        "zh": "我们坐飞机去北京旅游。",
        "ja": "私たちは飛行機で北京へ旅行に行きます。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s08.mp3",
        "pinyin": "wǒ men zuò fēi jī qù běi jīng lǚ yóu。"
      },
      {
        "n": 9,
        "zh": "这件衣服太贵，我们去别的商店看看吧。",
        "ja": "この服は高すぎるので、別のお店を見に行きましょう。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s09.mp3",
        "pinyin": "zhè jiàn yī fú tài guì， wǒ men qù bié de shāng diàn kàn kàn ba。"
      },
      {
        "n": 10,
        "zh": "你身体好吗？",
        "ja": "お体の調子はいかがですか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s10.mp3",
        "pinyin": "nǐ shēn tǐ hǎo ma？"
      },
      {
        "n": 11,
        "zh": "他非常会打篮球。",
        "ja": "彼はバスケットボールがとても上手です。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s11.mp3",
        "pinyin": "tā fēi cháng huì dǎ lán qiú。"
      },
      {
        "n": 12,
        "zh": "这是我第一次来中国。",
        "ja": "これは私が初めて中国に来たことです。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s12.mp3",
        "pinyin": "zhè shì wǒ dì yī cì lái zhōng guó。"
      },
      {
        "n": 13,
        "zh": "我姐姐在医院工作，是医生。",
        "ja": "私の姉は病院で働いていて、医者です。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s13.mp3",
        "pinyin": "wǒ jiě jiě zài yī yuàn gōng zuò， shì yī shēng。"
      },
      {
        "n": 14,
        "zh": "请问，火车站在哪儿？",
        "ja": "すみません、駅はどこですか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s14.mp3",
        "pinyin": "qǐng wèn， huǒ chē zhàn zài nǎ ér？"
      },
      {
        "n": 15,
        "zh": "我想买一些水果。",
        "ja": "私は果物をいくつか買いたいです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s15.mp3",
        "pinyin": "wǒ xiǎng mǎi yī xiē shuǐ guǒ。"
      },
      {
        "n": 16,
        "zh": "昨天晚上我看了电视，也看了书。",
        "ja": "昨日の夜、私はテレビを見て、本も読みました。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s16.mp3",
        "pinyin": "zuó tiān wǎn shàng wǒ kàn le diàn shì， yě kàn le shū。"
      },
      {
        "n": 17,
        "zh": "你几岁了？",
        "ja": "あなたは何歳ですか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s17.mp3",
        "pinyin": "nǐ jǐ suì le？"
      },
      {
        "n": 18,
        "zh": "我们坐出租车去机场，好吗？",
        "ja": "タクシーで空港へ行きませんか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s18.mp3",
        "pinyin": "wǒ men zuò chū zū chē qù jī chǎng， hǎo ma？"
      },
      {
        "n": 19,
        "zh": "我在教室里学习汉语。",
        "ja": "私は教室で中国語を勉強しています。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s19.mp3",
        "pinyin": "wǒ zài jiào shì lǐ xué xí hàn yǔ。"
      },
      {
        "n": 20,
        "zh": "我姐姐在饭店工作。",
        "ja": "私の姉はホテル(レストラン)で働いています。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s20.mp3",
        "pinyin": "wǒ jiě jiě zài fàn diàn gōng zuò。"
      },
      {
        "n": 21,
        "zh": "我想买一些水果和鸡蛋。",
        "ja": "私は果物と卵をいくつか買いたいです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s21.mp3",
        "pinyin": "wǒ xiǎng mǎi yī xiē shuǐ guǒ hé jī dàn。"
      },
      {
        "n": 22,
        "zh": "我今天早上喝了牛奶，也吃了鸡蛋。",
        "ja": "私は今日の朝、牛乳を飲んで、卵も食べました。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s22.mp3",
        "pinyin": "wǒ jīn tiān zǎo shàng hē le niú nǎi， yě chī le jī dàn。"
      },
      {
        "n": 23,
        "zh": "这个西瓜很好吃。",
        "ja": "このスイカはとても美味しいです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s23.mp3",
        "pinyin": "zhè ge xī guā hěn hǎo chī。"
      },
      {
        "n": 24,
        "zh": "你几点起床？",
        "ja": "あなたは何時に起きますか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s24.mp3",
        "pinyin": "nǐ jǐ diǎn qǐ chuáng？"
      },
      {
        "n": 25,
        "zh": "我们下个星期有一个汉语考试。",
        "ja": "私たちは来週、中国語の試験があります。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s25.mp3",
        "pinyin": "wǒ men xià gè xīng qī yǒu yí gè hàn yǔ kǎo shì。"
      },
      {
        "n": 26,
        "zh": "我朋友请我喝咖啡。",
        "ja": "友達が私にコーヒーをおごってくれました。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s26.mp3",
        "pinyin": "wǒ péng yǒu qǐng wǒ hē kā fēi。"
      },
      {
        "n": 27,
        "zh": "这个电脑是你的吗？",
        "ja": "このパソコンはあなたのものですか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s27.mp3",
        "pinyin": "zhè ge diàn nǎo shì nǐ de ma？"
      },
      {
        "n": 28,
        "zh": "我想去饭店吃羊肉。",
        "ja": "私はレストランへ羊肉を食べに行きたいです。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s28.mp3",
        "pinyin": "wǒ xiǎng qù fàn diàn chī yáng ròu。"
      },
      {
        "n": 29,
        "zh": "他非常喜欢运动，也喜欢游泳。",
        "ja": "彼はスポーツがとても好きで、水泳も好きです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_002/s29.mp3",
        "pinyin": "tā fēi cháng xǐ huān yùn dòng， yě xǐ huān yóu yǒng。"
      },
      {
        "n": 30,
        "zh": "你觉得这个电影怎么样？",
        "ja": "あなたはこの映画についてどう思いますか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_002/s30.mp3",
        "pinyin": "nǐ jué de zhè ge diàn yǐng zěn me yàng？"
      }
    ],
    "key": "hsk2/set_002"
  },
  {
    "id": "set_003",
    "title": "HSK2 リスニング 1文ずつ (3)",
    "level": "HSK2",
    "sentences": [
      {
        "n": 1,
        "zh": "现在下雪了，天气很冷。",
        "ja": "今、雪が降っていて、天気はとても寒いです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s01.mp3",
        "pinyin": "xiàn zài xià xuě le， tiān qì hěn lěng。"
      },
      {
        "n": 2,
        "zh": "我姐姐比我大三岁。",
        "ja": "私の姉は私より3歳年上です。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s02.mp3",
        "pinyin": "wǒ jiě jiě bǐ wǒ dà sān suì。"
      },
      {
        "n": 3,
        "zh": "你的手机在桌子上。",
        "ja": "あなたの携帯電話は机の上にあります。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s03.mp3",
        "pinyin": "nǐ de shǒu jī zài zhuō zi shàng。"
      },
      {
        "n": 4,
        "zh": "我爸爸是老师，我妈妈是医生。",
        "ja": "私の父は先生で、母は医者です。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s04.mp3",
        "pinyin": "wǒ bà bà shì lǎo shī， wǒ mā mā shì yī shēng。"
      },
      {
        "n": 5,
        "zh": "你喜欢什么颜色？我喜欢红的和白的。",
        "ja": "あなたは何色が好きですか。私は赤と白が好きです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s05.mp3",
        "pinyin": "nǐ xǐ huān shén me yán sè？ wǒ xǐ huān hóng de hé bái de。"
      },
      {
        "n": 6,
        "zh": "请你等一下，我五分钟就到。",
        "ja": "少し待ってください、5分で着きます。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s06.mp3",
        "pinyin": "qǐng nǐ děng yí xià， wǒ wǔ fēn zhōng jiù dào。"
      },
      {
        "n": 7,
        "zh": "你的手表几点了？",
        "ja": "あなたの腕時計は何時ですか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s07.mp3",
        "pinyin": "nǐ de shǒu biǎo jǐ diǎn le？"
      },
      {
        "n": 8,
        "zh": "我们中午一起吃米饭吧。",
        "ja": "お昼に一緒にご飯を食べましょう。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s08.mp3",
        "pinyin": "wǒ men zhōng wǔ yì qǐ chī mǐ fàn ba。"
      },
      {
        "n": 9,
        "zh": "你的房间很大。",
        "ja": "あなたの部屋はとても広いです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s09.mp3",
        "pinyin": "nǐ de fáng jiān hěn dà。"
      },
      {
        "n": 10,
        "zh": "他晚上运动，身体很好。",
        "ja": "彼は夜に運動していて、体がとても丈夫です。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s10.mp3",
        "pinyin": "tā wǎn shàng yùn dòng， shēn tǐ hěn hǎo。"
      },
      {
        "n": 11,
        "zh": "我想请你去饭店吃鱼，可以吗？",
        "ja": "レストランへ魚を食べに行くのにご招待したいのですが、いいですか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s11.mp3",
        "pinyin": "wǒ xiǎng qǐng nǐ qù fàn diàn chī yú， kě yǐ ma？"
      },
      {
        "n": 12,
        "zh": "请问，医院怎么走？",
        "ja": "すみません、病院へはどう行けばいいですか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s12.mp3",
        "pinyin": "qǐng wèn， yī yuàn zěn me zǒu？"
      },
      {
        "n": 13,
        "zh": "我在火车站等你。",
        "ja": "私は駅であなたを待っています。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s13.mp3",
        "pinyin": "wǒ zài huǒ chē zhàn děng nǐ。"
      },
      {
        "n": 14,
        "zh": "这个问题他不知道，你知道吗？",
        "ja": "この問題を彼は知りません、あなたは知っていますか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s14.mp3",
        "pinyin": "zhè ge wèn tí tā bù zhī dào， nǐ zhī dào ma？"
      },
      {
        "n": 15,
        "zh": "我今天很高兴，因为明天是星期六。",
        "ja": "私は今日とても嬉しいです、明日が土曜日だからです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s15.mp3",
        "pinyin": "wǒ jīn tiān hěn gāo xìng， yīn wèi míng tiān shì xīng qī liù。"
      },
      {
        "n": 16,
        "zh": "你今天穿的衣服很漂亮。",
        "ja": "あなたが今日着ている服はとてもきれいです。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s16.mp3",
        "pinyin": "nǐ jīn tiān chuān de yī fú hěn piào liàng。"
      },
      {
        "n": 17,
        "zh": "我朋友送了我一本书。",
        "ja": "友達が私に本を1冊くれました。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s17.mp3",
        "pinyin": "wǒ péng yǒu sòng le wǒ yī běn shū。"
      },
      {
        "n": 18,
        "zh": "你叫什么名字？",
        "ja": "あなたの名前は何ですか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s18.mp3",
        "pinyin": "nǐ jiào shén me míng zì？"
      },
      {
        "n": 19,
        "zh": "我在公司等你。",
        "ja": "私は会社であなたを待っています。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s19.mp3",
        "pinyin": "wǒ zài gōng sī děng nǐ。"
      },
      {
        "n": 20,
        "zh": "他的书还在教室里。",
        "ja": "彼の本はまだ教室の中にあります。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s20.mp3",
        "pinyin": "tā de shū hái zài jiào shì lǐ。"
      },
      {
        "n": 21,
        "zh": "我今天很忙，没有时间休息。",
        "ja": "私は今日とても忙しくて、休む時間がありません。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s21.mp3",
        "pinyin": "wǒ jīn tiān hěn máng， méi yǒu shí jiān xiū xī。"
      },
      {
        "n": 22,
        "zh": "你要不要和我们一起去看电影？",
        "ja": "私たちと一緒に映画を見に行きませんか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s22.mp3",
        "pinyin": "nǐ yào bù yào hé wǒ men yì qǐ qù kàn diàn yǐng？"
      },
      {
        "n": 23,
        "zh": "我姐姐是老师，她在学校工作。",
        "ja": "私の姉は先生で、学校で働いています。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s23.mp3",
        "pinyin": "wǒ jiě jiě shì lǎo shī， tā zài xué xiào gōng zuò。"
      },
      {
        "n": 24,
        "zh": "这儿很远，我们坐公共汽车去吧。",
        "ja": "ここは遠いので、バスで行きましょう。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s24.mp3",
        "pinyin": "zhè ér hěn yuǎn， wǒ men zuò gōng gòng qì chē qù ba。"
      },
      {
        "n": 25,
        "zh": "我想给你打电话。",
        "ja": "私はあなたに電話をかけたいです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s25.mp3",
        "pinyin": "wǒ xiǎng gěi nǐ dǎ diàn huà。"
      },
      {
        "n": 26,
        "zh": "你今天为什么不高兴？",
        "ja": "あなたは今日どうして嬉しくないのですか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s26.mp3",
        "pinyin": "nǐ jīn tiān wèi shén me bù gāo xìng？"
      },
      {
        "n": 27,
        "zh": "我们的老师非常好。",
        "ja": "私たちの先生はとても良い人です。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s27.mp3",
        "pinyin": "wǒ men de lǎo shī fēi cháng hǎo。"
      },
      {
        "n": 28,
        "zh": "我想和你说一件事情。",
        "ja": "あなたに1つ話したいことがあります。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s28.mp3",
        "pinyin": "wǒ xiǎng hé nǐ shuō yī jiàn shì qíng。"
      },
      {
        "n": 29,
        "zh": "我在家看电视，也在家吃米饭。",
        "ja": "私は家でテレビを見て、家でご飯も食べます。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk2/set_003/s29.mp3",
        "pinyin": "wǒ zài jiā kàn diàn shì， yě zài jiā chī mǐ fàn。"
      },
      {
        "n": 30,
        "zh": "你们公司在哪儿？",
        "ja": "あなたたちの会社はどこにありますか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk2/set_003/s30.mp3",
        "pinyin": "nǐ men gōng sī zài nǎ ér？"
      }
    ],
    "key": "hsk2/set_003"
  },
  {
    "id": "set_001",
    "title": "HSK3 リスニング 1文ずつ (1)",
    "level": "HSK3",
    "sentences": [
      {
        "n": 1,
        "zh": "我打算下个星期六去爬山。",
        "ja": "私は来週の土曜日に山登りに行くつもりです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s01.mp3",
        "pinyin": "wǒ dǎ suàn xià gè xīng qī liù qù pá shān。"
      },
      {
        "n": 2,
        "zh": "这件衬衫是我姐姐送给我的生日礼物。",
        "ja": "このシャツは姉が私にくれた誕生日プレゼントです。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s02.mp3",
        "pinyin": "zhè jiàn chèn shān shì wǒ jiě jiě sòng gěi wǒ de shēng rì lǐ wù。"
      },
      {
        "n": 3,
        "zh": "虽然刮风了，但是天气还是很好。",
        "ja": "風が吹いていますが、天気はやはり良いです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s03.mp3",
        "pinyin": "suī rán guā fēng le， dàn shì tiān qì hái shì hěn hǎo。"
      },
      {
        "n": 4,
        "zh": "我把护照忘记在家里了，现在很着急。",
        "ja": "パスポートを家に忘れてしまい、今とても焦っています。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s04.mp3",
        "pinyin": "wǒ bǎ hù zhào wàng jì zài jiā lǐ le， xiàn zài hěn zháo jí。"
      },
      {
        "n": 5,
        "zh": "他被经理叫到了办公室。",
        "ja": "彼はマネージャーにオフィスに呼ばれました。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s05.mp3",
        "pinyin": "tā bèi jīng lǐ jiào dào le bàn gōng shì。"
      },
      {
        "n": 6,
        "zh": "我觉得这个句子的意思不太清楚，你能再讲一次吗？",
        "ja": "この文の意味があまりはっきりしないと思います、もう一度説明してもらえますか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s06.mp3",
        "pinyin": "wǒ jué de zhè ge jù zi de yì si bù tài qīng chǔ， nǐ néng zài jiǎng yī cì ma？"
      },
      {
        "n": 7,
        "zh": "除了游泳，他还喜欢打篮球和骑自行车。",
        "ja": "水泳のほかに、彼はバスケットボールと自転車に乗るのも好きです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s07.mp3",
        "pinyin": "chú le yóu yǒng， tā hái xǐ huān dǎ lán qiú hé qí zì xíng chē。"
      },
      {
        "n": 8,
        "zh": "如果明天不下雨，我们就去公园锻炼身体。",
        "ja": "もし明日雨が降らなければ、私たちは公園へ体を鍛えに行きます。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s08.mp3",
        "pinyin": "rú guǒ míng tiān bù xià yǔ， wǒ men jiù qù gōng yuán duàn liàn shēn tǐ。"
      },
      {
        "n": 9,
        "zh": "我最近感冒了，一直发烧，也不想吃东西。",
        "ja": "私は最近風邪を引いて、ずっと熱があり、何も食べたくありません。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s09.mp3",
        "pinyin": "wǒ zuì jìn gǎn mào le， yì zhí fā shāo， yě bù xiǎng chī dōng xī。"
      },
      {
        "n": 10,
        "zh": "这家超市附近有一个很大的图书馆。",
        "ja": "このスーパーの近くに大きな図書館があります。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s10.mp3",
        "pinyin": "zhè jiā chāo shì fù jìn yǒu yí gè hěn dà de tú shū guǎn。"
      },
      {
        "n": 11,
        "zh": "她的中文水平提高得很快，说得也越来越好。",
        "ja": "彼女の中国語のレベルは急速に上達していて、話すのもますます上手になっています。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s11.mp3",
        "pinyin": "tā de zhōng wén shuǐ píng tí gāo dé hěn kuài， shuō dé yě yuè lái yuè hǎo。"
      },
      {
        "n": 12,
        "zh": "我们坐地铁去比较方便，还是坐出租车去？",
        "ja": "地下鉄で行くほうが便利ですか、それともタクシーで行きますか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s12.mp3",
        "pinyin": "wǒ men zuò dì tiě qù bǐ jiào fāng biàn， hái shì zuò chū zū chē qù？"
      },
      {
        "n": 13,
        "zh": "经理让我明天早上八点参加一个重要的会议。",
        "ja": "マネージャーは私に明日の朝8時に重要な会議に出席するように言いました。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s13.mp3",
        "pinyin": "jīng lǐ ràng wǒ míng tiān zǎo shàng bā diǎn cān jiā yí gè zhòng yào de huì yì。"
      },
      {
        "n": 14,
        "zh": "我打扫了房间，也洗了衣服，然后去超市买东西。",
        "ja": "私は部屋を掃除して、洗濯もして、それからスーパーへ買い物に行きました。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s14.mp3",
        "pinyin": "wǒ dǎ sǎo le fáng jiān， yě xǐ le yī fú， rán hòu qù chāo shì mǎi dōng xī。"
      },
      {
        "n": 15,
        "zh": "这条裤子有点儿大，你能不能换一条小一点儿的？",
        "ja": "このズボンは少し大きいです、もう少し小さいものに交換してもらえますか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s15.mp3",
        "pinyin": "zhè tiáo kù zi yǒu diǎn ér dà， nǐ néng bù néng huàn yī tiáo xiǎo yì diǎn ér de？"
      },
      {
        "n": 16,
        "zh": "我记得他的生日是九月二十号，是不是？",
        "ja": "彼の誕生日は9月20日だったと思いますが、そうですよね。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s16.mp3",
        "pinyin": "wǒ jì de tā de shēng rì shì jiǔ yuè èr shí hào， shì bú shì？"
      },
      {
        "n": 17,
        "zh": "别难过了，这件事情不是你的错。",
        "ja": "悲しまないで、この件はあなたのせいではありません。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s17.mp3",
        "pinyin": "bié nán guò le， zhè jiàn shì qíng bú shì nǐ de cuò。"
      },
      {
        "n": 18,
        "zh": "我打算学习游泳，但是一直没有机会。",
        "ja": "私は水泳を習うつもりですが、ずっと機会がありません。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s18.mp3",
        "pinyin": "wǒ dǎ suàn xué xí yóu yǒng， dàn shì yì zhí méi yǒu jī huì。"
      },
      {
        "n": 19,
        "zh": "这个故事很有意思，我看了两次还想再看。",
        "ja": "この物語はとても面白くて、2回読んでもまた読みたいです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s19.mp3",
        "pinyin": "zhè ge gù shì hěn yǒu yì si， wǒ kàn le liǎng cì hái xiǎng zài kàn。"
      },
      {
        "n": 20,
        "zh": "请把这张照片发到我的电子邮件里。",
        "ja": "この写真を私のメールに送ってください。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s20.mp3",
        "pinyin": "qǐng bǎ zhè zhāng zhào piān fā dào wǒ de diàn zi yóu jiàn lǐ。"
      },
      {
        "n": 21,
        "zh": "我们公司附近新开了一家商店，环境很安静。",
        "ja": "私たちの会社の近くに新しく店ができて、環境がとても静かです。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s21.mp3",
        "pinyin": "wǒ men gōng sī fù jìn xīn kāi le yī jiā shāng diàn， huán jìng hěn ān jìng。"
      },
      {
        "n": 22,
        "zh": "他虽然很努力，但是这次考试成绩不太好。",
        "ja": "彼はとても努力しましたが、今回の試験の成績はあまり良くありませんでした。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s22.mp3",
        "pinyin": "tā suī rán hěn nǔ lì， dàn shì zhè cì kǎo shì chéng jì bù tài hǎo。"
      },
      {
        "n": 23,
        "zh": "你放心，这个问题我们一定会想办法解决的。",
        "ja": "安心してください、この問題は私たちが必ず方法を考えて解決します。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s23.mp3",
        "pinyin": "nǐ fàng xīn， zhè ge wèn tí wǒ men yí dìng huì xiǎng bàn fǎ jiě jué de。"
      },
      {
        "n": 24,
        "zh": "我打算这个周末去银行换一点儿钱。",
        "ja": "私は今週末、銀行へお金を両替しに行くつもりです。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s24.mp3",
        "pinyin": "wǒ dǎ suàn zhè ge zhōu mò qù yín háng huàn yì diǎn ér qián。"
      },
      {
        "n": 25,
        "zh": "她一边听音乐，一边做作业。",
        "ja": "彼女は音楽を聴きながら宿題をしています。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s25.mp3",
        "pinyin": "tā yī biān tīng yīn yuè， yī biān zuò zuò yè。"
      },
      {
        "n": 26,
        "zh": "这个包太大了，一个人拿不了，你能不能来帮忙？",
        "ja": "このカバンは大きすぎて、一人では持てません、手伝いに来てもらえますか。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s26.mp3",
        "pinyin": "zhè ge bāo tài dà le， yí gè rén ná bù liǎo， nǐ néng bù néng lái bāng máng？"
      },
      {
        "n": 27,
        "zh": "我们先去吃点儿东西，然后再去看电影，怎么样？",
        "ja": "先に何か食べてから、それから映画を見に行くのはどうですか。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s27.mp3",
        "pinyin": "wǒ men xiān qù chī diǎn ér dōng xī， rán hòu zài qù kàn diàn yǐng， zěn me yàng？"
      },
      {
        "n": 28,
        "zh": "我对中国历史很感兴趣。",
        "ja": "私は中国の歴史にとても興味があります。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s28.mp3",
        "pinyin": "wǒ duì zhōng guó lì shǐ hěn gǎn xìng qù。"
      },
      {
        "n": 29,
        "zh": "他终于决定跟女朋友结婚了。",
        "ja": "彼はついに彼女と結婚することを決めました。",
        "voice": "zh-CN-XiaoxiaoNeural",
        "audio": "audio/hsk3/set_001/s29.mp3",
        "pinyin": "tā zhōng yú jué dìng gēn nǚ péng yǒu jié hūn le。"
      },
      {
        "n": 30,
        "zh": "你的手机忘记在办公室了，我给你拿过来了。",
        "ja": "あなたの携帯電話をオフィスに忘れましたよ、持ってきてあげました。",
        "voice": "zh-CN-YunxiNeural",
        "audio": "audio/hsk3/set_001/s30.mp3",
        "pinyin": "nǐ de shǒu jī wàng jì zài bàn gōng shì le， wǒ gěi nǐ ná guò lái le。"
      }
    ],
    "key": "hsk3/set_001"
  }
];
