// generated by gen_vocab.py -- do not edit
window.VOCAB_DATA = [
  {
    "id": "set_001",
    "title": "HSK2 単語想起テスト 1",
    "level": "HSK2",
    "items": [
      {
        "n": 1,
        "ja": "この服はとても**安い**です。",
        "word": "便宜",
        "pinyin": "pianyi",
        "tones_full": "25",
        "tones_compact": "2"
      },
      {
        "n": 2,
        "ja": "彼はいつも**忙しい**です。",
        "word": "忙",
        "pinyin": "mang",
        "tones_full": "2",
        "tones_compact": "2"
      },
      {
        "n": 3,
        "ja": "私の**姉**は医者です。",
        "word": "姐姐",
        "pinyin": "jiejie",
        "tones_full": "33",
        "tones_compact": "33"
      },
      {
        "n": 4,
        "ja": "**コーヒー**を1杯ください。",
        "word": "咖啡",
        "pinyin": "kafei",
        "tones_full": "11",
        "tones_compact": "11"
      },
      {
        "n": 5,
        "ja": "あなたの**助け**が必要です。",
        "word": "帮助",
        "pinyin": "bangzhu",
        "tones_full": "14",
        "tones_compact": "14"
      },
      {
        "n": 6,
        "ja": "この言葉の**意味**が分かりません。",
        "word": "意思",
        "pinyin": "yisi",
        "tones_full": "45",
        "tones_compact": "4"
      },
      {
        "n": 7,
        "ja": "私はこれが面白いと**思います**。",
        "word": "觉得",
        "pinyin": "juede",
        "tones_full": "25",
        "tones_compact": "2"
      },
      {
        "n": 8,
        "ja": "私はあなたに来てほしいと**望みます**。",
        "word": "希望",
        "pinyin": "xiwang",
        "tones_full": "14",
        "tones_compact": "14"
      },
      {
        "n": 9,
        "ja": "**駅**はどこですか。",
        "word": "火车站",
        "pinyin": "huochezhan",
        "tones_full": "314",
        "tones_compact": "314"
      },
      {
        "n": 10,
        "ja": "**店員**さん、お会計をお願いします。",
        "word": "服务员",
        "pinyin": "fuwuyuan",
        "tones_full": "242",
        "tones_compact": "242"
      },
      {
        "n": 11,
        "ja": "私の**弟**は学生です。",
        "word": "弟弟",
        "pinyin": "didi",
        "tones_full": "45",
        "tones_compact": "4"
      },
      {
        "n": 12,
        "ja": "私の**兄**は会社員です。",
        "word": "哥哥",
        "pinyin": "gege",
        "tones_full": "11",
        "tones_compact": "11"
      },
      {
        "n": 13,
        "ja": "私の**妹**はまだ小学生です。",
        "word": "妹妹",
        "pinyin": "meimei",
        "tones_full": "44",
        "tones_compact": "44"
      },
      {
        "n": 14,
        "ja": "これは私の**部屋**です。",
        "word": "房间",
        "pinyin": "fangjian",
        "tones_full": "21",
        "tones_compact": "21"
      },
      {
        "n": 15,
        "ja": "彼は**会社**で働いています。",
        "word": "公司",
        "pinyin": "gongsi",
        "tones_full": "11",
        "tones_compact": "11"
      },
      {
        "n": 16,
        "ja": "学生たちは**教室**にいます。",
        "word": "教室",
        "pinyin": "jiaoshi",
        "tones_full": "44",
        "tones_compact": "44"
      },
      {
        "n": 17,
        "ja": "今日は私の**誕生日**です。",
        "word": "生日",
        "pinyin": "shengri",
        "tones_full": "14",
        "tones_compact": "14"
      },
      {
        "n": 18,
        "ja": "**時間**がありません。",
        "word": "时间",
        "pinyin": "shijian",
        "tones_full": "21",
        "tones_compact": "21"
      },
      {
        "n": 19,
        "ja": "これは私の**携帯電話**です。",
        "word": "手机",
        "pinyin": "shouji",
        "tones_full": "31",
        "tones_compact": "31"
      },
      {
        "n": 20,
        "ja": "これは簡単な**問題**です。",
        "word": "问题",
        "pinyin": "wenti",
        "tones_full": "42",
        "tones_compact": "42"
      },
      {
        "n": 21,
        "ja": "あなたはどんな**色**が好きですか。",
        "word": "颜色",
        "pinyin": "yanse",
        "tones_full": "24",
        "tones_compact": "24"
      },
      {
        "n": 22,
        "ja": "彼女の**目**はとてもきれいです。",
        "word": "眼睛",
        "pinyin": "yanjing",
        "tones_full": "31",
        "tones_compact": "31"
      },
      {
        "n": 23,
        "ja": "**体**に気をつけてください。",
        "word": "身体",
        "pinyin": "shenti",
        "tones_full": "13",
        "tones_compact": "13"
      },
      {
        "n": 24,
        "ja": "彼は**病気になりました**。",
        "word": "生病",
        "pinyin": "shengbing",
        "tones_full": "14",
        "tones_compact": "14"
      },
      {
        "n": 25,
        "ja": "**運動**は健康にいいです。",
        "word": "运动",
        "pinyin": "yundong",
        "tones_full": "44",
        "tones_compact": "44"
      },
      {
        "n": 26,
        "ja": "私は**水泳**が好きです。",
        "word": "游泳",
        "pinyin": "youyong",
        "tones_full": "23",
        "tones_compact": "23"
      },
      {
        "n": 27,
        "ja": "私たちは中国へ**旅行**に行きます。",
        "word": "旅游",
        "pinyin": "lvyou",
        "tones_full": "32",
        "tones_compact": "32"
      },
      {
        "n": 28,
        "ja": "明日は**試験**があります。",
        "word": "考试",
        "pinyin": "kaoshi",
        "tones_full": "34",
        "tones_compact": "34"
      },
      {
        "n": 29,
        "ja": "**スイカ**は好きですか。",
        "word": "西瓜",
        "pinyin": "xigua",
        "tones_full": "11",
        "tones_compact": "11"
      },
      {
        "n": 30,
        "ja": "**卵**を1つください。",
        "word": "鸡蛋",
        "pinyin": "jidan",
        "tones_full": "14",
        "tones_compact": "14"
      }
    ],
    "key": "hsk2/set_001"
  }
];
